package com.revature.models;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

// Java Bean

public class Student implements Serializable {
	
	private static int GLOBAL_ID= 1000;
	
	private String firstName;
	private String lastName;
	private int gradeYear; // 1 - Freshman , 2 - Sophomore
	private String studentId; // we have to concaternate the gradeyear plus an autogenerated ID
								// Every student has a list of course that they take
	private List<Course> course = new ArrayList<Course>(); // everytime we instantiate a new student
															// object, they will have an empty course list
	private double tuitionBalance = 0; // initalizing the balance

	// constructor will be FirstName, Lastname, gradeyear , 
	public Student(String firstName, String lastName, int gradeYear) {
		super();
		this.firstName = firstName;
		this.lastName = lastName;
		this.gradeYear = gradeYear;
		
		setStudentId();
		
		//when we call the construcor, lets sysout the instance variables
		System.out.println(firstName + " " + lastName + " " + gradeYear);
	}
	
	// it will autoincrement some value, 
	private void setStudentId(){
		GLOBAL_ID++;
		this.studentId = gradeYear + "" + GLOBAL_ID;
	}	
		
	public void enroll() {
		
	}

	@Override
	public int hashCode() {
		return Objects.hash(course, firstName, gradeYear, lastName, studentId, tuitionBalance);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Student other = (Student) obj;
		return Objects.equals(course, other.course) && Objects.equals(firstName, other.firstName)
				&& gradeYear == other.gradeYear && Objects.equals(lastName, other.lastName)
				&& Objects.equals(studentId, other.studentId)
				&& Double.doubleToLongBits(tuitionBalance) == Double.doubleToLongBits(other.tuitionBalance);
	}

	@Override
	public String toString() {
		return "Student [firstName=" + firstName + ", lastName=" + lastName + ", gradeYear=" + gradeYear
				+ ", studentId=" + studentId + ", course=" + course + ", tuitionBalance=" + tuitionBalance + "]";
	}

	
	




}
