# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{S3_BUCKET}}"
        # This is the folder where the "built" version of your src code will go
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        # We need node to install all the dependencies and built the distributable artifact
        nodejs: 12
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started
        # ng build is the command you use when you're ready to build your app
        # and deploy it. The CLI will analyze the application and build the
        # files, all while optimizing the application as best as it can.
        - ng build
artifacts:
    files:
        - '**/*'
        # The CLI will then output the files in the dist/your-project-name folder,
        # ready to be placed on a server and ready to be visited.
    base-directory: 'dist*'
    discard-paths: yes
