package com.revature.service;

import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.revature.data.FoodRepository;
import com.revature.model.Food;

@Service
public class FoodService {

	private Logger log = LoggerFactory.getLogger(this.getClass());
	
	// This class is responsible for calling the data layer
	// and its CRUD methods
	@Autowired
	private FoodRepository foodRepo;
	
	
	// add()
	public int add(Food food) {
		
		// Call the repository method to insert a Food Object into its respective table
		Food savedFood = foodRepo.save(food);
		
		// Once we save it in the DB, we can capture the primary key generated by the DB
		return savedFood.getId();
		
	}
	
	
	// finding food by dish name (using FoodRepository)
	public Food findFoodByDishName(String dishName) {
		
		Optional<Food> possibleFood =  foodRepo.findByDishNameIgnoreCase(dishName);
		
		return possibleFood.isPresent() ? possibleFood.get() : null;
		
	}
	
	
	// findAllFoods()
	public List<Food> findAllFoods(){
		
		return foodRepo.findAll(); // findAll method comes from the JpaRepository
		
	}
	
	
	// remove()
	public void deleteById(int id) {
		
		foodRepo.deleteById(id); // deleteById method from the Spring Framework
	}
	
	
	
}
